-- 1º ENCONTRAR DB ID DO SCHEMA
SELECT DB_ID, NAME, DB_LOCATION_URI 
FROM DBS
WHERE LOWER(NAME) = 'adm_sajadm';

-- 2º ENCONTRAR TABELAS DO SCHEMA
SELECT 
    GROUP_CONCAT(t.TBL_ID ORDER BY t.TBL_ID SEPARATOR ',') AS ids_concatenados,
    GROUP_CONCAT(d.NAME ORDER BY t.TBL_ID SEPARATOR ',') AS nomes
FROM TBLS t
JOIN DBS d ON d.DB_ID = t.DB_ID
WHERE d.DB_ID = :DB_ID
;

-- 3 DELETAR METADADOS DAS TABELAS
DELETE FROM metastore_db.TBL_PRIVS WHERE tbl_id IN (:TBL_ID);
DELETE FROM metastore_db.TABLE_PARAMS WHERE tbl_id IN (:TBL_ID);
DELETE FROM PARTITION_KEY_VALS 
WHERE PART_ID IN (select PART_ID from PARTITIONS
 WHERE tbl_id IN (:TBL_ID)
);
DELETE FROM PARTITION_PARAMS 
WHERE PART_ID IN (select PART_ID from PARTITIONS
 WHERE tbl_id IN (:TBL_ID)
);
DELETE FROM PARTITION_KEYS WHERE TBL_ID IN (:TBL_ID);
DELETE FROM metastore_db.PARTITIONS WHERE tbl_id IN (:TBL_ID);
DELETE FROM metastore_db.TBLS WHERE tbl_id IN (:TBL_ID);

-- Apagar Schema
DELETE FROM DBS
WHERE DB_ID =  :DB_ID;